FREE_TRADES_LIMIT = 250
FREE_ASSET_MOVEMENTS_LIMIT = 100
FREE_LEDGER_ACTIONS_LIMIT = 50

LIMITS_MAPPING = {
    'trade': FREE_TRADES_LIMIT,
    'asset_movement': FREE_ASSET_MOVEMENTS_LIMIT,
    'ledger_action': FREE_LEDGER_ACTIONS_LIMIT,
}
