KRAKEN_ACCOUNT_TYPE_KEY = 'kraken_account_type'
FTX_SUBACCOUNT_NAME_KEY = 'ftx_subaccount'
BINANCE_MARKETS_KEY = 'PAIRS'
USER_CREDENTIAL_MAPPING_KEYS = (
    KRAKEN_ACCOUNT_TYPE_KEY,
    FTX_SUBACCOUNT_NAME_KEY,
    BINANCE_MARKETS_KEY,
)
