KRAKEN_ACCOUNT_TYPE_KEY = 'kraken_account_type'
FTX_SUBACCOUNT_NAME_KEY = 'ftx_subaccount'
BINANCE_MARKETS_KEY = 'binance_selected_trade_pairs'
USER_CREDENTIAL_MAPPING_KEYS = (
    KRAKEN_ACCOUNT_TYPE_KEY,
    FTX_SUBACCOUNT_NAME_KEY,
    BINANCE_MARKETS_KEY,
)
HISTORY_MAPPING_CUSTOMIZED = 'customized'
HISTORY_MAPPING_DECODED = 'decoded'
ACCOUNTS_DETAILS_LAST_QUERIED_TS = 'last_queried_timestamp'
ACCOUNTS_DETAILS_TOKENS = 'tokens'
