KRAKEN_ACCOUNT_TYPE_KEY = 'kraken_account_type'
FTX_SUBACCOUNT_NAME_KEY = 'ftx_subaccount'
BINANCE_MARKETS_KEY = 'binance_selected_trade_pairs'
USER_CREDENTIAL_MAPPING_KEYS = (
    KRAKEN_ACCOUNT_TYPE_KEY,
    FTX_SUBACCOUNT_NAME_KEY,
    BINANCE_MARKETS_KEY,
)

# -- history_events_mappings values --
HISTORY_MAPPING_KEY_STATE = 'state'
HISTORY_MAPPING_STATE_DECODED = 0
HISTORY_MAPPING_STATE_CUSTOMIZED = 1


EVM_ACCOUNTS_DETAILS_LAST_QUERIED_TS = 'last_queried_timestamp'
EVM_ACCOUNTS_DETAILS_TOKENS = 'tokens'
