"""Defi Protocol List

This module handles the defi protocol list, stored in DEFI_PROTOCOLS.
"""
from typing import NamedTuple


class Protocol(NamedTuple):
    """Protocol class for representing airdrop data.

    This contains the definition of the Protocol class, which is used to represent
    individual protocolss along with their associated data, such as name, and icon filename.
    """
    name: str
    icon: str


DEFI_PROTOCOLS: dict[str, Protocol] = {
    'ygovfinancev1': Protocol('ygov.finance (v1)', 'iearn.png'),
    'ygovfinancev2': Protocol('ygov.finance (v2)', 'iearn.png'),
    'zlotfinance': Protocol('zlot.finance', 'zlotfinance.png'),
    'finnexus': Protocol('FinNexus', 'finnexus.svg'),
    'pickle_finance': Protocol('Pickle Finance', 'pickle.png'),
    'pickle_finance_farms': Protocol('Pickle Finance &bull; Farms', 'pickle.png'),
    'pickle_finance_staking': Protocol('Pickle Finance &bull; Staking', 'pickle.png'),
    'dodo': Protocol('DODO', 'dodo.svg'),
    'berezka': Protocol('Berezka', 'berezka.png'),
    'bzx': Protocol('bZx', 'bzx.svg'),
    'bzx_staking': Protocol('bZx &bull; Staking', 'bzx.svg'),
    'bzx_vested_staking': Protocol('bZx &bull; Vested Staking', 'bzx.svg'),
    'cream': Protocol('C.R.E.A.M.', 'cream.svg'),
    'cream_staking': Protocol('C.R.E.A.M. &bull; Staking', 'cream.svg'),
    'swerve': Protocol('Swerve', 'swerve.png'),
    'swerve_liquidity_gauges': Protocol('Swerve &bull; Liquidity Gauges', 'swerve.png'),
    'sashimiswap': Protocol('SashimiSwap', 'sashimi.png'),
    'harvest': Protocol('Harvest', 'harvest.svg'),
    'kimchi': Protocol('KIMCHI', 'kimchi.png'),
    'sushiswap': Protocol('SushiSwap', 'sushiswap.svg'),
    'sushiswap_staking': Protocol('SushiSwap &bull; Staking', 'sushiswap.svg'),
    'nexus_mutual': Protocol('Nexus Mutual', 'nexusmutual.jpg'),
    'mooniswap': Protocol('Mooniswap', 'mooniswap.svg'),
    'matic': Protocol('Matic', 'matic.svg'),
    'aragon': Protocol('Aragon', 'aragon.svg'),
    'melon': Protocol('Melon', 'melon.svg'),
    'enzyme': Protocol('Enzyme', 'enzyme.svg'),
    'yearn_vaults': Protocol('yearn.finance &bull; Vaults', 'yearn_vaults.svg'),
    'yearn_vaults_v2': Protocol('yearn.finance &bull; Vaults (v2)', 'yearn_vaults.svg'),
    'yearn_token_vaults': Protocol('Yearn Token Vaults', 'yearn_vaults.svg'),
    'keeperdao': Protocol('KeeperDAO', 'keeperdao.svg'),
    'mstable': Protocol('mStable', 'mstable.png'),
    'mstable_staking': Protocol('mStable &bull; Staking', 'mstable.png'),
    'mstable_v2': Protocol('mStable V2', 'mstable.png'),
    'kyberdao': Protocol('KyberDAO', 'kyber.svg'),
    'ddex_spot': Protocol('DDEX &bull; Spot', 'ddex.svg'),
    'ddex_margin': Protocol('DDEX &bull; Margin', 'ddex.svg'),
    'ddex_lending': Protocol('DDEX &bull; Lending', 'ddex.svg'),
    'ampleforth': Protocol('Ampleforth', 'ampl.svg'),
    'maker_governance': Protocol('Maker Governance', 'makerdao.svg'),
    'gnosis_protocol': Protocol('Gnosis Protocol', 'gnosis_protocol.png'),
    'chigastoken': Protocol('Chi Gastoken by 1inch', 'chi.png'),
    'uniswapv2': Protocol('Uniswap V2', 'uniswap.svg'),
    'piedao': Protocol('PieDAO', 'piedao.png'),
    'piedao_experipies': Protocol('PieDAO ExperiPies', 'piedao.png'),
    'multicollateral_dai': Protocol('Multi-Collateral Dai', 'dai.svg'),
    'bancor': Protocol('Bancor', 'bancor.svg'),
    'bancor_locked_bnt': Protocol('Bancor &bull; Locked BNT', 'bancor.svg'),
    'bancor_liquidity_protection': Protocol('Bancor &bull; Liquidity Protection', 'bancor.svg'),
    'defi_money_market': Protocol('DeFi Money Market', 'dmm.svg'),
    'tokensets': Protocol('TokenSets', 'set.svg'),
    'zerox_staking': Protocol('0x Staking', '0x_staking.svg'),
    'uniswapv1': Protocol('Uniswap V1', 'uniswap.svg'),
    'synthetix': Protocol('Synthetix', 'synthetix.svg'),
    'pooltogether': Protocol('PoolTogether', 'pooltogether.svg'),
    'pooltogether_v3': Protocol('PoolTogether V3', 'pooltogether.svg'),
    'dai_savings_rate': Protocol('Dai Savings Rate', 'makerdao.svg'),
    'chai': Protocol('Chai', 'chai.png'),
    'iearnfinancev3': Protocol('iearn.finance (v3)', 'iearn.png'),
    'iearnfinancev2': Protocol('iearn.finance (v2)', 'iearn.png'),
    'idle': Protocol('Idle', 'idle.svg'),
    'idle_riskadjusted': Protocol('Idle &bull; Risk-Adjusted', 'idle.svg'),
    'dydx': Protocol('dYdX', 'dydx.svg'),
    'curve': Protocol('Curve', 'curve.png'),
    'curve_vesting': Protocol('Curve &bull; Vesting', 'curve.png'),
    'curve_liquidity_gauges': Protocol('Curve &bull; Liquidity Gauges', 'curve.png'),
    'curve_vecrv': Protocol('Curve &bull; Vote Escrowed CRV', 'curve.png'),
    'compound': Protocol('Compound', 'compound.svg'),
    'compound_governance': Protocol('Compound Governance', 'compound.svg'),
    'balancer': Protocol('Balancer', 'balancer.svg'),
    'aave': Protocol('Aave', 'aave.svg'),
    'aave_staking': Protocol('Aave &bull; Staking', 'aave.svg'),
    'aave_uniswapmarket': Protocol('Aave &bull; Uniswap Market', 'aave.svg'),
    'makerdao_dsr': Protocol('MakerDAO DSR', 'makerdao.svg'),
    'makerdao_vaults': Protocol('MakerDAO Vaults', 'makerdao.svg'),
    'aave_v2': Protocol('Aave V2', 'aave.svg'),
    'aave_v2_variable_debt': Protocol('Aave V2 &bull; Variable Debt', 'aave.svg'),
    'aave_v2_stable_debt': Protocol('Aave V2 &bull; Stable Debt', 'aave.svg'),
    'snow_swap': Protocol('SnowSwap', 'snowswap.svg'),
    'harvest_profit_sharing': Protocol('Harvest &bull; Profit Sharing', 'harvest.svg'),
    'idle_early_rewards': Protocol('Idle &bull; Early Rewards', 'idle.svg'),
    'oneinch_liquidity': Protocol('1inch Liquidity Protocol', '1inch.svg'),
    'oneinch_lp_staking': Protocol('1inch LP &bull; Staking', '1inch.svg'),
    'mushrooms_finance': Protocol('Mushrooms Finance', 'mushroom.png'),
    'mushrooms_finance_staking': Protocol('Mushrooms Finance &bull; Staking', 'mushroom.png'),
    'akropolis_akro_staking': Protocol('Akropolis &bull; AKRO Staking', 'acropolis.svg'),
    'akropolis_adel_staking': Protocol('Akropolis &bull; ADEL Staking', 'acropolis.svg'),
    'liquity': Protocol('Liquity', 'liquity.png'),
    'alpha_homora': Protocol('Alpha Homora', 'alphahomorav2.png'),
    'alpha_homora_v2': Protocol('Alpha Homora V2', 'alphahomorav2.png'),
    'stake_dao': Protocol('Stake DAO', 'stakedao.png'),
    'saddle': Protocol('Saddle', 'saddle.svg'),
    'reflexer': Protocol('Reflexer', 'reflexer.png'),
    'cometh_tube': Protocol('Cometh &bull; Tube', 'cometh.jpg'),
    'cometh_staking': Protocol('Cometh &bull; Staking', 'cometh.jpg'),
    'livepeer': Protocol('Livepeer', 'livepeer.svg'),
    'cozy': Protocol('Cozy', 'cozy.svg'),
    'cozy_yearn': Protocol('Cozy &bull; Yearn', 'cozy.svg'),
    'cozy_compound': Protocol('Cozy &bull; Compound', 'cozy.svg'),
    'unagii': Protocol('Unagii', 'unagii.svg'),
    'origin_protocol': Protocol('Origin Protocol &bull; OGN Staking', 'origin.png'),
    'timewarp': Protocol('TimeWarp &bull; Staking', 'timewarp.png'),
    'gelato': Protocol('Gelato Network &bull; Locked GEL', 'gelato.svg'),
}
