custom: ['https://rotki.com/products/', 'https://github.com/rotki/rotki#donations', 'https://explorer.gitcoin.co/#/projects/0xca5797a71ca6f849ba9c366972d47c01061949d5cdf7fa61e20a229e035d877b', 'https://giveth.io/project/rotki?tab=donations']
github: ['rotki']
