from .sessions import Session
from .exceptions import ConnectionError

def get(url, params=None, **kwargs):...

def session():...

# class HTTPError(RequestException): ...
# class ConnectionError(RequestException): ...
