packages:
  - app
  - common
  - dev-proxy
  - 'eslint/*'

ignoredBuiltDependencies:
  - core-js-pure
  - cypress
  - msw

onlyBuiltDependencies:
  - electron
  - esbuild
  - '@parcel/watcher'
  - vue-demi
