allowUnusedPatches: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - app
  - common
  - dev-proxy
  - 'eslint/*'
overrides:
  yaml-eslint-parser: 1.3.2
patchedDependencies:
  bignumber.js@9.3.1: patches/bignumber.js@9.3.1.patch
onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - electron
  - electron-winstaller
  - esbuild
  - keccak
  - utf-8-validate
  - vue-demi
