"""
This script generates a minimized db schema (either user or global databases) for schema
sanity check and puts it either in rotkehlchen/db/minimized_schema.py or
rotkehlchen/globaldb/minimized_schema.py depending on the mode.
The mode is selected by passing either --db-name user or --db-name global.
"""

import argparse
import datetime
import re
from pathlib import Path
from typing import Literal

from rotkehlchen.db.checks import db_script_normalizer
from rotkehlchen.db.schema import (
    DB_CREATE_INDEXES as USER_DB_CREATE_INDEXES,
    DB_SCRIPT_CREATE_TABLES as USER_DB_CREATE_TABLES,
)
from rotkehlchen.globaldb.schema import (
    DB_CREATE_INDEXES as GLOBAL_DB_CREATE_INDEXES,
    DB_SCRIPT_CREATE_TABLES as GLOBAL_DB_CREATE_TABLES,
)
from rotkehlchen.utils.misc import get_system_spec

p = argparse.ArgumentParser()
p.add_argument(
    '--db-name',
    help='Type of the db for which to generate minimized schema',
    type=str,
    choices=['user', 'global'],
    required=True,
)
p.add_argument(
    '--author',
    help='Who is running this script? Used just for informational purposes',
    type=str,
    required=True,
)
args = p.parse_args()
db_name: Literal['user', 'global'] = args.db_name

# Make dictionary of table_name: table_properties. Without whitespaces. For example:
# this {"ens_mappings": "CREATETABLEIFNOTEXISTSens_mappings(addressTEXTNOTNULLPRIMARYKEY,ens_nameTEXTUNIQUE,last_updateINTEGERNOTNULL);"}  # noqa: E501
db_script = USER_DB_CREATE_TABLES if db_name == 'user' else GLOBAL_DB_CREATE_TABLES
index_script = USER_DB_CREATE_INDEXES if db_name == 'user' else GLOBAL_DB_CREATE_INDEXES
regexp_result = re.findall(
    pattern=r'createtableifnotexists(.+?)\((.+?)\);',
    # Replacing new lines and white spaces since they may vary if by an accident code of a
    # db upgrade was a bit different from the one that creates new tables
    string=db_script_normalizer(db_script),
)

lines = [
    '# This file contains minimized db schema and it should not be touched manually but only generated by tools/scripts/generate_minimized_db_schema.py',  # noqa: E501
]

created_at = datetime.datetime.now(tz=datetime.UTC).strftime('%Y-%m-%d %H:%M:%S')
rotki_version = get_system_spec()['rotkehlchen']
lines.extend((
    f'# Created at {created_at} UTC with rotki version {rotki_version} by {args.author}',
    f'MINIMIZED_{db_name.upper()}_DB_SCHEMA = {{',
))
for name, properties in regexp_result:
    lines.append(f'    "{name}": "{properties}",')
lines.append('}')

# Parse indexes by first extracting each CREATE INDEX/CREATE UNIQUE statement
index_regexp_result = []
index_pattern = re.compile(
    r'CREATE\s+(UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS\s+(\S+)\s+ON\s+(\S+)\s*\(([^)]+)\)(.*)$',
    re.IGNORECASE,
)
for entry in index_script.strip().split(';'):
    statement = entry.strip()
    if statement and (_match := index_pattern.match(statement)):
        is_unique = _match.group(1) is not None
        index_name = _match.group(2).lower()
        table_name = _match.group(3).lower()
        columns = _match.group(4).lower().replace(' ', '')
        where_clause = _match.group(5).strip() if _match.group(5) else ''
        index_regexp_result.append((index_name, table_name, columns, is_unique, where_clause))

lines.extend(('', f'MINIMIZED_{db_name.upper()}_DB_INDEXES = {{'))
for index_name, table_name, columns, is_unique, where_clause in index_regexp_result:
    prefix = 'createuniqueindexifnotexists' if is_unique else 'createindexifnotexists'
    where_part = where_clause.lower().replace(' ', '') if len(where_clause) > 0 else where_clause
    index_definition = f'{prefix}{index_name}on{table_name}({columns}){where_part}'
    lines.append(f'    "{index_name}": "{index_definition}",')
lines.append('}')

# Save to the file
db_module = 'db' if db_name == 'user' else 'globaldb'
Path(f'rotkehlchen/{db_module}/minimized_schema.py').write_text('\n'.join(lines) + '\n', encoding='utf8')  # noqa: E501
