# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: all_common.proto
# Protobuf Python Version: 5.27.3
# isort: skip_file
# ruff: noqa: ERA001,E111,E501
# type: ignore
# flake8: noqa: E111
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'all_common.proto',
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ll_common.proto"9\n\x12PremiumCredentials\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x12\n\napi_secret\x18\x02 \x01(\t"\x9d\x01\n\nUnlockCall\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\ncreate_new\x18\x03 \x01(\x08\x12$\n\rsync_approval\x18\x04 \x01(\x0e\x32\r.SyncApproval\x12\x1a\n\x12resume_from_backup\x18\x05 \x01(\x08\x12\x15\n\rsync_database\x18\x06 \x01(\x08"2\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x04name\x18\x02 \x01(\x0e\x32\n.ErrorType"\'\n\nTypedArray\x12\x19\n\x05\x61rray\x18\x01 \x03(\x0b\x32\n.TypedData"P\n\tTypedData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x05\x62ytes\x18\x02 \x01(\x0cH\x00\x12\x1c\n\x05\x61rray\x18\x03 \x01(\x0b\x32\x0b.TypedArrayH\x00\x42\x06\n\x04\x64\x61ta"/\n\x03Set\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x18\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\n.TypedData*\x81\x01\n\tErrorType\x12\x0f\n\x0bMemoryError\x10\x00\x12\x13\n\x0fHostSystemError\x10\x01\x12\x14\n\x10ProgrammingError\x10\x02\x12\x14\n\x10\x43omputationError\x10\x03\x12\x10\n\x0c\x44\x42WriteError\x10\x04\x12\x10\n\x0cUnknownError\x10\x05*,\n\x0cSyncApproval\x12\x07\n\x03YES\x10\x00\x12\x06\n\x02NO\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'all_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORTYPE']._serialized_start = 464
  _globals['_ERRORTYPE']._serialized_end = 593
  _globals['_SYNCAPPROVAL']._serialized_start = 595
  _globals['_SYNCAPPROVAL']._serialized_end = 639
  _globals['_PREMIUMCREDENTIALS']._serialized_start = 20
  _globals['_PREMIUMCREDENTIALS']._serialized_end = 77
  _globals['_UNLOCKCALL']._serialized_start = 80
  _globals['_UNLOCKCALL']._serialized_end = 237
  _globals['_ERROR']._serialized_start = 239
  _globals['_ERROR']._serialized_end = 289
  _globals['_TYPEDARRAY']._serialized_start = 291
  _globals['_TYPEDARRAY']._serialized_end = 330
  _globals['_TYPEDDATA']._serialized_start = 332
  _globals['_TYPEDDATA']._serialized_end = 412
  _globals['_SET']._serialized_start = 414
  _globals['_SET']._serialized_end = 461
# @@protoc_insertion_point(module_scope)
