# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bg_worker.proto
# Protobuf Python Version: 5.27.3
# # isort: skip_file
# ruff: noqa: ERA001,E111,E501,I001
# type: ignore
# flake8: noqa: E111
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'bg_worker.proto',
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62g_worker.proto\x1a\x10\x61ll_common.proto"\xc7\x01\n\nBGCallData\x12"\n\x06method\x18\x01 \x01(\x0e\x32\x10.SchedulerMethodH\x00\x12\x19\n\x0fshould_schedule\x18\x02 \x01(\x08H\x00\x12\x1d\n\x06unlock\x18\x03 \x01(\x0b\x32\x0b.UnlockCallH\x00\x12*\n\x13maybe_kill_tx_query\x18\x04 \x01(\x0b\x32\x0b.TypedArrayH\x00\x12\'\n\x17\x62\x61se_entries_ignore_set\x18\x05 \x01(\x0b\x32\x04.SetH\x00\x42\x06\n\x04\x64\x61ta"4\n\x0c\x42GReturnData\x12\x1a\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x06.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error*?\n\x0fSchedulerMethod\x12\x0c\n\x08SCHEDULE\x10\x00\x12\t\n\x05\x43LEAR\x10\x01\x12\x13\n\x0fREFRESH_PREMIUM\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bg_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULERMETHOD']._serialized_start = 293
  _globals['_SCHEDULERMETHOD']._serialized_end = 356
  _globals['_BGCALLDATA']._serialized_start = 38
  _globals['_BGCALLDATA']._serialized_end = 237
  _globals['_BGRETURNDATA']._serialized_start = 239
  _globals['_BGRETURNDATA']._serialized_end = 291
# @@protoc_insertion_point(module_scope)
