# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_messages.proto
# Protobuf Python Version: 5.27.3
# isort: skip_file
# ruff: noqa: ERA001,E111,E501
# type: ignore
# flake8: noqa: E111
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'db_messages.proto',
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rotkehlchen.protobufs import all_common_pb2  # pylint: disable=unused-import  # noqa: F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x62_messages.proto\x1a\x10\x61ll_common.proto"4\n\rDBWriteResult\x12\x10\n\x08rowcount\x18\x01 \x01(\x05\x12\x11\n\tlastrowid\x18\x02 \x01(\x04"\x8c\x02\n\nDBCallData\x12*\n\x0f\x63onnection_type\x18\x01 \x01(\x0e\x32\x11.DBConnectionType\x12\x0f\n\x07\x64\x62_path\x18\x02 \x01(\t\x12\x18\n\x0b\x63ursor_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x06method\x18\x04 \x01(\x0e\x32\t.DBMethod\x12\x18\n\x04\x61rgs\x18\x05 \x03(\x0b\x32\n.TypedData\x12\'\n\x06kwargs\x18\x06 \x03(\x0b\x32\x17.DBCallData.KwargsEntry\x1a\x39\n\x0bKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.TypedData:\x02\x38\x01\x42\x0e\n\x0c_cursor_name"d\n\x0c\x44\x42ReturnData\x12#\n\x06result\x18\x01 \x01(\x0b\x32\x0e.DBWriteResultH\x00\x88\x01\x01\x12\x1a\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.ErrorH\x01\x88\x01\x01\x42\t\n\x07_resultB\x08\n\x06_error*7\n\x10\x44\x42\x43onnectionType\x12\x08\n\x04USER\x10\x00\x12\r\n\tTRANSIENT\x10\x01\x12\n\n\x06GLOBAL\x10\x02*\x93\x01\n\x08\x44\x42Method\x12\x0e\n\nINITIALIZE\x10\x00\x12\x0f\n\x0bOPEN_CURSOR\x10\x01\x12\x10\n\x0c\x43LOSE_CURSOR\x10\x02\x12\x0b\n\x07\x45XECUTE\x10\x03\x12\x0f\n\x0b\x45XECUTEMANY\x10\x04\x12\x11\n\rEXECUTESCRIPT\x10\x05\x12\x0c\n\x08ROLLBACK\x10\x06\x12\n\n\x06\x43OMMIT\x10\x07\x12\t\n\x05\x43LOSE\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DBCALLDATA_KWARGSENTRY']._loaded_options = None
  _globals['_DBCALLDATA_KWARGSENTRY']._serialized_options = b'8\001'
  _globals['_DBCONNECTIONTYPE']._serialized_start = 466
  _globals['_DBCONNECTIONTYPE']._serialized_end = 521
  _globals['_DBMETHOD']._serialized_start = 524
  _globals['_DBMETHOD']._serialized_end = 671
  _globals['_DBWRITERESULT']._serialized_start = 39
  _globals['_DBWRITERESULT']._serialized_end = 91
  _globals['_DBCALLDATA']._serialized_start = 94
  _globals['_DBCALLDATA']._serialized_end = 362
  _globals['_DBCALLDATA_KWARGSENTRY']._serialized_start = 289
  _globals['_DBCALLDATA_KWARGSENTRY']._serialized_end = 346
  _globals['_DBRETURNDATA']._serialized_start = 364
  _globals['_DBRETURNDATA']._serialized_end = 464
# @@protoc_insertion_point(module_scope)
