from typing import Final

ROTKI_EVENT_PREFIX: Final = 'RE'
COINTRACKING_EVENT_PREFIX: Final = 'COT'
COINLEDGER_EVENT_PREFIX: Final = 'CLD'
BITSTAMP_EVENT_PREFIX: Final = 'BTS'
BLOCKPIT_EVENT_PREFIX: Final = 'BPT'
COINBASEPRO_EVENT_PREFIX: Final = 'CBP'
