from typing import Final

VALIDATOR_STATS_QUERY_BACKOFF_EVERY_N_VALIDATORS = 30
VALIDATOR_STATS_QUERY_BACKOFF_TIME_RANGE = 20
VALIDATOR_STATS_QUERY_BACKOFF_TIME = 8

LAST_PRODUCED_BLOCKS_QUERY_TS: Final = 'last_produced_blocks_query_ts'
WITHDRAWALS_PREFIX: Final = 'ethwithdrawals'

FREE_VALIDATORS_LIMIT = 4
UNKNOWN_VALIDATOR_INDEX = -1

CPT_ETH2: Final = 'eth2'
