REQUEST_DELTA_TS = 60 * 60  # 1

VALIDATOR_STATS_QUERY_BACKOFF_EVERY_N_VALIDATORS = 30
VALIDATOR_STATS_QUERY_BACKOFF_TIME_RANGE = 20
VALIDATOR_STATS_QUERY_BACKOFF_TIME = 8

FREE_VALIDATORS_LIMIT = 4

CPT_ETH2 = 'eth2'
