from rotkehlchen.assets.asset import Asset, EthereumToken

A_RDN = EthereumToken('RDN')
A_GNO = EthereumToken('GNO')
A_DAO = EthereumToken('DAO')
A_DOGE = Asset('DOGE')
A_XMR = Asset('XMR')
A_DASH = Asset('DASH')
A_IOTA = Asset('IOTA')
A_BSV = Asset('BSV')
A_BCH = Asset('BCH')
A_GBP = Asset('GBP')
A_SNGLS = Asset('SNGLS')
A_BNB = Asset('BNB')
A_USDT = Asset('USDT')
A_LTC = Asset('LTC')
A_CNY = Asset('CNY')
