# from rotkehlchen.db.filtering import TradesFilterQuery
from rotkehlchen.exchanges.data_structures import Trade


def assert_trades_equal(t1: Trade, t2: Trade) -> None:
    """Checks 2 trades are equal. Has a tolerance for precision errors in real numbers
    since the precision generated by sqlite division is different to fval one

    """
    t1_dict = t1.__dict__
    for key, val in t1_dict.items():
        if key in ('rate', 'amount'):
            assert val.is_close(getattr(t2, key))
        else:
            assert val == getattr(t2, key)
