export enum TaskType {
  ADD_ACCOUNT = 'add_account',
  REMOVE_ACCOUNT = 'remove_account',
  TRADE_HISTORY = 'process_trade_history',
  QUERY_BLOCKCHAIN_BALANCES = 'query_blockchain_balances_async',
  QUERY_EXCHANGE_BALANCES = 'query_exchange_balances_async',
  QUERY_BALANCES = 'query_balances_async',
  DSR_BALANCE = 'dsr_balance',
  DSR_HISTORY = 'dsr_history',
  MAKEDAO_VAULTS = 'makerdao_vaults',
  MAKERDAO_VAULT_DETAILS = 'makerdao_vault_details',
  AAVE_BALANCES = 'aave_balances',
  AAVE_HISTORY = 'aave_history',
  DEFI_BALANCES = 'defi_balances',
  TRADES = 'trades',
  MOVEMENTS = 'movements',
  TX = 'tx',
  MANUAL_BALANCES = 'manual_balances',
  DEFI_COMPOUND_BALANCES = 'defi_compound_balances',
  DEFI_COMPOUND_HISTORY = 'defi_compound_history',
  DEFI_YEARN_VAULT_HISTORY = 'defi_yearn_vault_history',
  DEFI_YEARN_VAULT_BALANCES = 'defi_yearn_vault_balances',
  FORCE_SYNC = 'force_sync'
}
