export const Routes = {
  DEFI_OVERVIEW: '/defi/overview',
  DEFI_DEPOSITS: '/defi/deposits',
  DEFI_LIABILITIES: '/defi/liabilities',
  DEFI: '/defi',
  DEFI_DEPOSITS_PROTOCOLS: '/defi/deposits/protocols',
  DEFI_DEPOSITS_LIQUIDITY: '/defi/deposits/liquidity',
  DEFI_DEX_TRADES: '/defi/dex-trades',
  STAKING: '/staking',
  STAKING_ETH2: '/staking/eth2',
  STAKING_ADEX: '/staking/adex',
  DEFI_AIRDROPS: '/defi/airdrops',
  PROFIT_LOSS_REPORT: '/profit-loss-report',
  HISTORY_LEDGER_ACTIONS: '/history/ledger-actions',
  HISTORY_GITCOIN: '/history/gitcoin',
  ASSETS: '/assets/:identifier',
  DEFI_DEPOSITS_LIQUIDITY_UNISWAP: '/defi/deposits/liquidity/uniswap',
  DEFI_DEPOSITS_LIQUIDITY_BALANCER: '/defi/deposits/liquidity/balancer',
  ASSET_MANAGER: '/asset-manager',
  PRICE_MANAGER: '/price-manager',
  DASHBOARD: '/dashboard',
  ROOT: '/'
};
