export enum Status {
  NONE,
  LOADING,
  REFRESHING,
  PARTIALLY_LOADED,
  LOADED,
}

export enum Section {
  NONE,
  HISTORY,
  BLOCKCHAIN,
  STAKING_ETH2,
  STAKING_ETH2_DEPOSITS,
  STAKING_ETH2_STATS,
  STAKING_KRAKEN,
  PRICES,
  EXCHANGES,
  EXCHANGE_SAVINGS,
  MANUAL_BALANCES,
  DEFI_LIQUITY_BALANCES,
  DEFI_LIQUITY_STAKING,
  DEFI_LIQUITY_STAKING_POOLS,
  DEFI_LIQUITY_STATISTICS,
  NON_FUNGIBLE_BALANCES,
  POOLS_SUSHISWAP,
  POOLS_UNISWAP_V2,
}
