export const IPC_RESTART_BACKEND = 'RESTART_BACKEND';

export const IPC_REQUEST_RESTART = 'REQUEST_RESTART';

export const IPC_BACKEND_PROCESS_DETECTED = 'BACKEND_PROCESS_DETECTED';

export const IPC_CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';

export const IPC_DOWNLOAD_UPDATE = 'DOWNLOAD_UPDATE';

export const IPC_DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS';

export const IPC_INSTALL_UPDATE = 'INSTALL_UPDATE';

export const IPC_THEME = 'THEME';

export const IPC_VERSION = 'VERSION';

export const IPC_IS_MAC = 'IS_MAC';

export const IPC_ABOUT = 'ABOUT';

export const IPC_OPEN_PATH = 'OPEN_PATH';

export const IPC_CONFIG = 'CONFIG';

export const IPC_METAMASK_IMPORT = 'METAMASK_IMPORT';

export const IPC_SERVER_URL = 'SERVER_URL';

export const IPC_GET_DEBUG = 'GET_DEBUG';

export const IPC_OPEN_URL = 'OPEN_URL';

export const IPC_OPEN_DIRECTORY = 'OPEN_DIRECTORY';

export const IPC_DEBUG_SETTINGS = 'DEBUG_SETTINGS';

export const IPC_CLOSE_APP = 'CLOSE_APP';

export const IPC_PREMIUM_LOGIN = 'PREMIUM_USER_LOGGED_IN';

export const IPC_TRAY_UPDATE = 'TRAY_UPDATE';

export const IPC_LOG_TO_FILE = 'LOG_TO_FILE';

export const IPC_STORE_PASSWORD = 'STORE_PASSWORD';

export const IPC_GET_PASSWORD = 'GET_PASSWORD';

export const IPC_CLEAR_PASSWORD = 'CLEAR_PASSWORD';
