# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_messages.proto
# Protobuf Python Version: 5.27.3
# isort: skip_file
# ruff: noqa: ERA001,E111,E501
# type: ignore
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'db_messages.proto',
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x62_messages.proto"4\n\rDBWriteResult\x12\x10\n\x08rowcount\x18\x01 \x01(\x05\x12\x11\n\tlastrowid\x18\x02 \x01(\x04"8\n\rDBWriterError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\x04name\x18\x02 \x01(\x0e\x32\x08.DBError"\'\n\nTypedArray\x12\x19\n\x05\x61rray\x18\x01 \x03(\x0b\x32\n.TypedData"P\n\tTypedData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x05\x62ytes\x18\x02 \x01(\x0cH\x00\x12\x1c\n\x05\x61rray\x18\x03 \x01(\x0b\x32\x0b.TypedArrayH\x00\x42\x06\n\x04\x64\x61ta"\x8e\x02\n\x0bZMQCallData\x12*\n\x0f\x63onnection_type\x18\x01 \x01(\x0e\x32\x11.DBConnectionType\x12\x0f\n\x07\x64\x62_path\x18\x02 \x01(\t\x12\x18\n\x0b\x63ursor_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x06method\x18\x04 \x01(\x0e\x32\t.DBMethod\x12\x18\n\x04\x61rgs\x18\x05 \x03(\x0b\x32\n.TypedData\x12(\n\x06kwargs\x18\x06 \x03(\x0b\x32\x18.ZMQCallData.KwargsEntry\x1a\x39\n\x0bKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.TypedData:\x02\x38\x01\x42\x0e\n\x0c_cursor_name"m\n\rZMQReturnData\x12#\n\x06result\x18\x01 \x01(\x0b\x32\x0e.DBWriteResultH\x00\x88\x01\x01\x12"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0e.DBWriterErrorH\x01\x88\x01\x01\x42\t\n\x07_resultB\x08\n\x06_error*7\n\x10\x44\x42\x43onnectionType\x12\x08\n\x04USER\x10\x00\x12\r\n\tTRANSIENT\x10\x01\x12\n\n\x06GLOBAL\x10\x02*\x93\x01\n\x08\x44\x42Method\x12\x0e\n\nINITIALIZE\x10\x00\x12\x0f\n\x0bOPEN_CURSOR\x10\x01\x12\x10\n\x0c\x43LOSE_CURSOR\x10\x02\x12\x0b\n\x07\x45XECUTE\x10\x03\x12\x0f\n\x0b\x45XECUTEMANY\x10\x04\x12\x11\n\rEXECUTESCRIPT\x10\x05\x12\x0c\n\x08ROLLBACK\x10\x06\x12\n\n\x06\x43OMMIT\x10\x07\x12\t\n\x05\x43LOSE\x10\x08*\x7f\n\x07\x44\x42\x45rror\x12\x0f\n\x0bMemoryError\x10\x00\x12\x13\n\x0fHostSystemError\x10\x01\x12\x14\n\x10ProgrammingError\x10\x02\x12\x14\n\x10\x43omputationError\x10\x03\x12\x10\n\x0c\x44\x42WriteError\x10\x04\x12\x10\n\x0cUnknownError\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_ZMQCALLDATA_KWARGSENTRY']._loaded_options = None
    _globals['_ZMQCALLDATA_KWARGSENTRY']._serialized_options = b'8\001'
    _globals['_DBCONNECTIONTYPE']._serialized_start = 640
    _globals['_DBCONNECTIONTYPE']._serialized_end = 695
    _globals['_DBMETHOD']._serialized_start = 698
    _globals['_DBMETHOD']._serialized_end = 845
    _globals['_DBERROR']._serialized_start = 847
    _globals['_DBERROR']._serialized_end = 974
    _globals['_DBWRITERESULT']._serialized_start = 21
    _globals['_DBWRITERESULT']._serialized_end = 73
    _globals['_DBWRITERERROR']._serialized_start = 75
    _globals['_DBWRITERERROR']._serialized_end = 131
    _globals['_TYPEDARRAY']._serialized_start = 133
    _globals['_TYPEDARRAY']._serialized_end = 172
    _globals['_TYPEDDATA']._serialized_start = 174
    _globals['_TYPEDDATA']._serialized_end = 254
    _globals['_ZMQCALLDATA']._serialized_start = 257
    _globals['_ZMQCALLDATA']._serialized_end = 527
    _globals['_ZMQCALLDATA_KWARGSENTRY']._serialized_start = 454
    _globals['_ZMQCALLDATA_KWARGSENTRY']._serialized_end = 511
    _globals['_ZMQRETURNDATA']._serialized_start = 529
    _globals['_ZMQRETURNDATA']._serialized_end = 638
# @@protoc_insertion_point(module_scope)
