from typing import Final

from rotkehlchen.types import SolanaAddress

SYSTEM_PROGRAM: Final = SolanaAddress('11111111111111111111111111111111')
SPL_TOKEN_PROGRAM: Final = SolanaAddress('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA')
TOKEN_2022_PROGRAM: Final = SolanaAddress('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb')
NATIVE_TRANSFER_DELIMITER: Final = b'\x02\x00\x00\x00'
SPL_TOKEN_TRANSFER_DELIMITER: Final = b'\x03'
SPL_TOKEN_TRANSFER_CHECKED_DELIMITER: Final = b'\x0c'
SPL_TOKEN_TRANSFER_CHECKED_WITH_FEE_DELIMITER: Final = b'\x1a'
SPL_TOKEN_TRANSFER_CHECKED_DELIMITERS: Final = (
    SPL_TOKEN_TRANSFER_CHECKED_DELIMITER,
    SPL_TOKEN_TRANSFER_CHECKED_WITH_FEE_DELIMITER,
)
