name: Rotki Nightly Builds

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - build

jobs:

  build-linux:
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        python-version: [ 3.9 ]
        node-version: [ 16.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: pip cache persistence
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-packaging-${{ hashFiles('**/requirements.txt') }}
      - name: npm cache persistence
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/cache/Cypress
            ./frontend/app/components.d.ts
          key: ${{ matrix.os }}-node--packaging-${{ hashFiles('**/app/package-lock.json') }}
      - name: Setup SQLCipher
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          ./install_deps.sh
          sudo ldconfig
      - name: Package
        id: packaging
        run: |
          npm install -g npm@8
          pip3 install --upgrade pip
          ./package.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightly-linux
          path: |
            ${{ steps.packaging.outputs.binary }}
            ${{ steps.packaging.outputs.binary_checksum }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'


  build-macos:
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: macos_sign
    strategy:
      matrix:
        os: [ macos-10.15 ]
        python-version: [ 3.9 ]
        node-version: [ 16.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        run: packaging/setup-osx.sh
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: pip cache persistence
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: ${{ matrix.os }}-pip-packaging-${{ hashFiles('**/requirements.txt') }}
      - name: npm cache persistence
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/Library/Caches/Cypress
          key: ${{ matrix.os }}-node--packaging-${{ hashFiles('**/app/package-lock.json') }}
      - name: Setup SQLCipher
        run: |
          cd "$(brew --repo homebrew/core)"
          git checkout 9ad779deb6076d0fc251fddc579ee2eb72acbb99 Formula/sqlcipher.rb #This formula installs 4.5.0 of sqlcipher
          brew install sqlcipher
      - name: Package
        id: packaging
        run: |
          pip3 install --upgrade pip
          pip3 install virtualenv
          python3 -m virtualenv ~/venv
          source ~/venv/bin/activate
          npm install -g npm@8
          ./package.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          IDENTITY: ${{ secrets.IDENTITY }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightly-osx
          path: |
            ${{ steps.packaging.outputs.binary }}
            ${{ steps.packaging.outputs.binary_checksum }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'

  build-windows:
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SQLCIPHER_VERSION: 'v4.5.0'
      PYSQLCIPHER3_VERSION: '1f1b703b9e35205946c820e735f58799e1b72d2d'
      BUILD_DEPENDENCIES: "build-dependencies"
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ 3.9 ]
        node-version: [ 16.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: pip cache persistence
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ matrix.os }}-pip-packaging-${{ hashFiles('**/requirements.txt') }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: npm cache persistence
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            ~\AppData\Local\Cypress
            .\frontend\app\components.d.ts
          key: ${{ matrix.os }}-node--packaging-${{ hashFiles('**/app/package-lock.json') }}
      - name: Persist Build Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~\${{ env.BUILD_DEPENDENCIES }}\
            ~\AppData\Local\Temp\chocolatey\
          key: ${{ matrix.os }}-build-dependencies-${{ env.SQLCIPHER_VERSION }}-${{ env.PYSQLCIPHER3_VERSION }}
      - name: Build rotki
        id: packaging
        run: |
          npm install -g npm@8
          pip3 install --upgrade pip
          .\package.ps1
        shell: powershell
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightly-windows
          path: |
            ${{ steps.packaging.outputs.binary }}
            ${{ steps.packaging.outputs.binary_checksum }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          $uri="${{ secrets.WEBHOOK }}"
          $body = @{
            "content" = ":construction_site: **Github Actions:** ${{ github.job }} failed :x: <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          } | ConvertTo-Json
          Invoke-RestMethod -Method Post -Uri $uri -ContentType "application/json" -Body $body

  build-docker:
    runs-on: ubuntu-18.04
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Rotki Version
        id: rotki_version
        run: |
          ROTKI_VERSION=$(cat .bumpversion.cfg | grep 'current_version = ' | sed -n -e 's/current_version = //p')
          POSTFIX=$(if git describe --tags --exact-match "$REVISION" &>/dev/null; then echo ''; else echo '-dev'; fi)
          ROTKI_VERSION=${ROTKI_VERSION}${POSTFIX}-$(date +'%Y.%m.%d')
          echo "::set-output name=version::${ROTKI_VERSION}"
      - name: Build Information
        id: build_information
        run: |
          if [[ "$GITHUB_EVENT_NAME" == 'schedule' ]]; then
            PLATFORMS='linux/amd64,linux/arm64'
            TAG=nightly
          else
            PLATFORMS=linux/amd64
            TAG=dev
          fi
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=platforms::$PLATFORMS"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.build_information.outputs.platforms }}
          push: true
          tags: rotki/rotki:${{ steps.build_information.outputs.tag }}
          build-args: |
            REVISION=${{ github.sha }}
            ROTKI_VERSION=${{ steps.rotki_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'
